name: Analysis DAST in front-end using ZAP
on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  # Environment variables for the workflow
  CALCULATOR_FRONTEND_URL: https://nachobc82-calculator-frontend.azurewebsites.net/

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          target: '${{ env.CALCULATOR_FRONTEND_URL }}'